ci: fixing release workflow

diff --git a/.github/workflows/build-release.yml b/.github/workflows/build-release.yml
--- a/.github/workflows/build-release.yml
+++ b/.github/workflows/build-release.yml
@@ -24,13 +24,14 @@ jobs:
   prechecks:
     runs-on: ubuntu-latest
     outputs:
-      version: ${{ steps.version.outputs.prop }}
+      version: ${{ steps.version.outputs.version }}
       need-new-tag: ${{ steps.check-tag.outputs.need-new-tag }}
     steps:
       - name: Checkout
         uses: actions/checkout@v3
 
       - name: get version
+        id: version
         run: |
           sudo apt-get -y install jq
           version=$(jq -r .version package.json)
@@ -67,13 +68,13 @@ jobs:
         id: semver-check
         run: |
           chmod +x .github/workflows/*.sh
-          .github/workflows/check-semver-syntax.sh ${{ steps.version.outputs.prop }}
+          .github/workflows/check-semver-syntax.sh ${{ steps.version.outputs.version }}
 
       - name: Check tag consistency
         if: startsWith(github.ref, 'refs/tags/')
         run: |
-          if [ "${{ steps.version.outputs.prop }}" != "${GITHUB_REF##*/}" ]; then
-            echo "Version in package.json does not match tag name: ${{ steps.version.outputs.prop }} != ${GITHUB_REF##*/}"
+          if [ "${{ steps.version.outputs.version }}" != "${GITHUB_REF##*/}" ]; then
+            echo "Version in package.json does not match tag name: ${{ steps.version.outputs.version }} != ${GITHUB_REF##*/}"
             exit 1
           fi
 
@@ -91,27 +92,31 @@ jobs:
         id: version
         run: |
           echo "version=${{ needs.prechecks.outputs.version }}" >> $GITHUB_ENV
+          if [ "x${{ needs.prechecks.outputs.version }}" == "x" ]; then
+            echo "Unable to extract version"
+            exit 1
+          fi
 
       # Re-check semver syntax in case this is being triggered by a manual tag push
       - name: Check semver syntax
         if: steps.check_tagged.outputs.need_tag == 'true'
         id: semver-check
         run: |
-          chmod +x .github/scripts/*.sh
-          .github/scripts/check-semver.sh ${{ steps.version.outputs.prop }}
+          chmod +x .github/workflows/*.sh
+          .github/workflows/check-semver-syntax.sh ${{ needs.prechecks.outputs.version }}
 
       - name: Check tag consistency
         if: startsWith(github.ref, 'refs/tags/')
         run: |
-          if [ "${{ steps.version.outputs.prop }}" != "${GITHUB_REF##*/}" ]; then
-            echo "Version in package.json does not match tag name: ${{ steps.version.outputs.prop }} != ${GITHUB_REF##*/}"
+          if [ "${{ needs.prechecks.outputs.version }}" != "${GITHUB_REF##*/}" ]; then
+            echo "Version in package.json does not match tag name: ${{ needs.prechecks.outputs.version }} != ${GITHUB_REF##*/}"
             exit 1
           fi
 
       - name: Set Environment Variables
         run: |
-          echo "zipFile=${{ env.packageName }}-${{ steps.version.outputs.prop }}".zip >> $GITHUB_ENV
-          echo "unityPackage=${{ env.packageName }}-${{ steps.version.outputs.prop }}.unitypackage" >> $GITHUB_ENV
+          echo "zipFile=${{ env.packageName }}-${{ needs.prechecks.outputs.version }}".zip >> $GITHUB_ENV
+          echo "unityPackage=${{ env.packageName }}-${{ needs.prechecks.outputs.version }}.unitypackage" >> $GITHUB_ENV
 
       - name: Create Zip
         uses: thedoctor0/zip-release@a24011d8d445e4da5935a7e73c1f98e22a439464
@@ -135,8 +140,8 @@ jobs:
         run: |
           git config user.name "Github Actions"
           git config user.email "github-actions@nadena.dev"
-          git tag ${{ steps.version.outputs.prop }}
-          git push origin ${{ steps.version.outputs.prop }}
+          git tag ${{ needs.prechecks.outputs.version }}
+          git push origin ${{ needs.prechecks.outputs.version }}
 
       - name: Make Release
         uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
@@ -144,8 +149,8 @@ jobs:
         with:
           draft: true
           generate_release_notes: true
-          tag_name: ${{ steps.version.outputs.prop }}
-          name: ${{ steps.version.outputs.prop }}
+          tag_name: ${{ needs.prechecks.outputs.version }}
+          name: ${{ needs.prechecks.outputs.version }}
           files: |
             ${{ env.zipFile }}
             package.json
