ci: adjust changelog check

diff --git a/.github/workflows/changelog-check.yml b/.github/workflows/changelog-check.yml
--- a/.github/workflows/changelog-check.yml
+++ b/.github/workflows/changelog-check.yml
@@ -38,17 +38,17 @@ jobs:
           PR_NUM: ${{ github.event.number }}
         run: |
           gh pr view $PR_NUM --json=files | jq --raw-output '.files[].path' > files.txt
+#      - name: Changelog check for CHANGELOG.md
+#        if: always() && !(env.NO_CHANGELOG || env.SNAPSHOT_ONLY)
+#        run: |
+#          if ! grep -e '^CHANGELOG.md$' < files.txt > /dev/null; then
+#            echo "::error::master branch is not ready for major release"
+#            exit 1
+#          fi
       - name: Changelog check for CHANGELOG.md
-        if: always() && !(env.NO_CHANGELOG || env.SNAPSHOT_ONLY)
-        run: |
-          if ! grep -e '^CHANGELOG.md$' < files.txt > /dev/null; then
-            echo "::error::master branch is not ready for major release"
-            exit 1
-          fi
-      - name: Changelog check for CHANGELOG-PRERELEASE.md
         if: always() && !env.NO_CHANGELOG
         run: |
-          if ! grep -e '^CHANGELOG-PRERELEASE.md' < files.txt > /dev/null; then
-            echo "::error::CHANGELOG-PRERELEASE.md is not updated!"
+          if ! grep -e '^CHANGELOG.md' < files.txt > /dev/null; then
+            echo "::error::CHANGELOG.md is not updated!"
             exit 1
           fi
