ci: fix changelog check

diff --git a/.github/workflows/changelog-check.yml b/.github/workflows/changelog-check.yml
--- a/.github/workflows/changelog-check.yml
+++ b/.github/workflows/changelog-check.yml
@@ -19,6 +19,10 @@ jobs:
   releasenote-check:
     if: ${{ ! github.event.pull_request.draft }}
     runs-on: ubuntu-latest
+    
+    strategy:
+      matrix:
+        file: [CHANGELOG.md, CHANGELOG-PRERELEASE.md]
 
     env:
       NO_CHANGELOG: ${{
@@ -27,10 +31,15 @@ jobs:
         || contains(github.event.pull_request.labels.*.name, 'localization')
         || contains(github.event.pull_request.labels.*.name, 'ci')
         || contains(github.event.pull_request.labels.*.name, 'refactor')
+        || startsWith(github.event.pull_request.head.label, 'bdunderscore:dependabot/')
         || '' }}
-      SNAPSHOT_ONLY: ${{ contains(github.event.pull_request.labels.*.name, 'SNAPSHOT-ONLY') || '' }}
+      SNAPSHOT_ONLY: ${{ contains(github.event.pull_request.labels.*.name, 'PRERELEASE-ONLY') || '' }}
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
+      - name: Dump GitHub context
+        env:
+          GITHUB_CONTEXT: ${{ toJson(github) }}
+        run: echo "$GITHUB_CONTEXT"
       - name: Fetch pull_request info
         env:
           GH_REPO: ${{ github.repositoryUrl }}
@@ -38,17 +47,12 @@ jobs:
           PR_NUM: ${{ github.event.number }}
         run: |
           gh pr view $PR_NUM --json=files | jq --raw-output '.files[].path' > files.txt
-#      - name: Changelog check for CHANGELOG.md
-#        if: always() && !(env.NO_CHANGELOG || env.SNAPSHOT_ONLY)
-#        run: |
-#          if ! grep -e '^CHANGELOG.md$' < files.txt > /dev/null; then
-#            echo "::error::master branch is not ready for major release"
-#            exit 1
-#          fi
-      - name: Changelog check for CHANGELOG.md
-        if: always() && !env.NO_CHANGELOG
+      - name: Changelog check for ${{ matrix.file }}
+        if: always() && !env.NO_CHANGELOG && (startsWith(matrix.file, 'CHANGELOG-PRERELEASE') || !env.SNAPSHOT_ONLY)
         run: |
-          if ! grep -e '^CHANGELOG.md' < files.txt > /dev/null; then
-            echo "::error::CHANGELOG.md is not updated!"
+          if ! grep -e '^${{ matrix.file }}$' < files.txt > /dev/null; then
+            echo "::error::An entry in ${{ matrix.file }} is required for this PR."
+            echo "If this change is only relevant between snapshot versions: Add the label 'PRERELEASE-ONLY' to this PR." >> $GITHUB_STEP_SUMMARY
+            echo "If this change does not warrant any release notes: Add the label 'NO-CHANGELOG' to this PR." >> $GITHUB_STEP_SUMMARY
             exit 1
           fi
